import {
  expireProduct01,
  expireProduct02,
  expireProduct03,
  expireProduct04,
  stockImg01,
  stockImg02,
  stockImg03,
  stockImg04,
  stockImg05,
  stockImg06,
  user02,
  user04,
  user05,
  user08,
  user09,
  user10,
  user11,
  user13,
  user30,
  user32 } from
"../../utils/imagepath";

export const ProductsData = [
{
  id: "1",
  image: stockImg01,
  SKU: "PT001",
  Product_Name: "Lenovo IdeaPad 3",
  Category: "Computers",
  Brand: "Lenovo",
  Price: "$600",
  Unit: "Pc",
  Qty: "100",
  Created_By: "James Kirwin",
  profile_image: { user30 }
},
{
  id: "2",
  image: stockImg06,
  SKU: "PT002",
  Product_Name: "Beats Pro",
  Category: "Electronics",
  Brand: "Beats",
  Price: "$160",
  Unit: "Pc",
  Qty: "140",
  Created_By: "Francis Chang",
  profile_image: { user13 }
},
{
  id: "3",
  image: stockImg02,
  SKU: "PT003",
  Product_Name: "Nike Jordan",
  Category: "Shoe",
  Brand: "Nike",
  Price: "$110",
  Unit: "Pc",
  Qty: "300",
  Created_By: "Antonio Engle",
  profile_image: { user11 }
},
{
  id: "4",
  image: stockImg03,
  SKU: "PT004",
  Product_Name: "Apple Series 5 Watch",
  Category: "Electronics",
  Brand: "Apple",
  Price: "$120",
  Unit: "Pc",
  Qty: "450",
  Created_By: "Leo Kelly",
  profile_image: { user32 }
},
{
  id: "5",
  image: stockImg04,
  SKU: "PT005",
  Product_Name: "Amazon Echo Dot",
  Category: "Electronics",
  Brand: "Amazon",
  Price: "$80",
  Unit: "Pc",
  Qty: "320",
  Created_By: "Annette Walker",
  profile_image: { user02 }
},
{
  id: "6",
  image: stockImg05,
  SKU: "PT006",
  Product_Name: "Sanford Chair Sofa",
  Category: "Furnitures",
  Brand: "Modern Wave",
  Price: "$320",
  Unit: "Pc",
  Qty: "650",
  Created_By: "John Weaver",
  profile_image: { user05 }
},
{
  id: "7",
  image: expireProduct01,
  SKU: "PT007",
  Product_Name: "Red Premium Satchel",
  Category: "Bags",
  Brand: "Dior",
  Price: "$60",
  Unit: "Pc",
  Qty: "700",
  Created_By: "Gary Hennessy",
  profile_image: { user08 }
},
{
  id: "8",
  image: expireProduct02,
  SKU: "PT008",
  Product_Name: "Iphone 14 Pro",
  Category: "Phone",
  Brand: "Apple",
  Price: "$540",
  Unit: "Pc",
  Qty: "630",
  Created_By: "Eleanor Panek",
  profile_image: { user04 }
},
{
  id: "9",
  image: expireProduct03,
  SKU: "PT009",
  Product_Name: "Gaming Chair",
  Category: "Furniture",
  Brand: "Arlime",
  Price: "$200",
  Unit: "Pc",
  Qty: "410",
  Created_By: "William Levy",
  profile_image: { user09 }
},
{
  id: "10",
  image: { expireProduct04 },
  SKU: "PT010",
  Product_Name: "Borealis Backpack",
  Category: "Bags",
  Brand: "The North Face",
  Price: "$45",
  Unit: "Pc",
  Qty: "550",
  Created_By: "Charlotte Klotz",
  profile_image: { user10 }
},
{
  id: "11",
  image: { expireProduct04 },
  SKU: "PT010",
  Product_Name: "Borealis Backpack",
  Category: "Bags",
  Brand: "The North Face",
  Price: "$45",
  Unit: "Pc",
  Qty: "550",
  Created_By: "Charlotte Klotz",
  profile_image: { user10 }
}];