import {
  stockImg1,
  user30,
  stockImg06,
  user13,
  stockImg02,
  user11,
  stockImg03,
  stockImg04,
  stockImg05,
  user05,
  expireProduct01,
  expireProduct02,
  user04,
  expireProduct03,
  user01,
  expireProduct04,
  user10,
  user02,
  user03,
  user08 } from
"../../utils/imagepath";

export const productlistdata = [
{
  id: 1,
  product: "Lenovo 3rd Generation",
  productImage: { stockImg1 },
  sku: "PT001",
  category: "Laptop",
  brand: "Lenovo",
  price: "$12500.00",
  unit: "Pc",
  qty: "100",
  createdby: "Arroon",
  img: { user30 }
},
{
  id: 2,
  product: "Bold V3.2",
  productImage: { stockImg06 },
  sku: "PT002",
  category: "Electronics",
  brand: "Bolt",
  price: "$1600.00",
  unit: "Pc",
  qty: "140",
  createdby: "Kenneth",
  img: { user13 }
},
{
  id: 3,
  product: "Nike Jordan",
  productImage: { stockImg02 },
  sku: "PT003",
  category: "Shoe",
  brand: "Nike",
  price: "$6000.00",
  unit: "Pc",
  qty: "780",
  createdby: "Gooch",
  img: { user11 }
},
{
  id: 4,
  product: "Apple Series 5 Watch",
  productImage: { stockImg03 },
  sku: "PT004",
  category: "Electronics",
  brand: "Apple",
  price: "$25000.00",
  unit: "Pc",
  qty: "450",
  createdby: "Nathan",
  img: { user03 }
},
{
  id: 5,
  product: "Amazon Echo Dot",
  productImage: { stockImg04 },
  sku: "PT005",
  category: "Speaker",
  brand: "Amazon",
  price: "$1600.00",
  unit: "Pc",
  qty: "477",
  createdby: "Alice",
  img: { user02 }
},
{
  id: 6,
  product: "Lobar Handy",
  productImage: { stockImg05 },
  sku: "PT006",
  category: "Furnitures",
  brand: "Woodmart",
  price: "$4521.00",
  unit: "Kg",
  qty: "145",
  createdby: "Robb",
  img: { user05 }
},
{
  id: 7,
  product: "Red Premium Handy",
  productImage: { expireProduct01 },
  sku: "PT007",
  category: "Bags",
  brand: "Versace",
  price: "$2024.00",
  unit: "Kg",
  qty: "747",
  createdby: "Steven",
  img: { user08 }
},
{
  id: 8,
  product: "Iphone 14 Pro",
  productImage: { expireProduct02 },
  sku: "PT008",
  category: "Phone",
  brand: "Iphone",
  price: "$1698.00",
  unit: "Pc",
  qty: "897",
  createdby: "Gravely",
  img: { user04 }
},
{
  id: 9,
  product: "Black Slim 200",
  productImage: { expireProduct03 },
  sku: "PT009",
  category: "Chairs",
  brand: "Bently",
  price: "$6794.00",
  unit: "Pc",
  qty: "741",
  createdby: "Kevin",
  img: { user01 }
},
{
  id: 10,
  product: "Woodcraft Sandal",
  productImage: { expireProduct04 },
  sku: "PT010",
  category: "Bags",
  brand: "Woodcraft",
  price: "$4547.00",
  unit: "Kg",
  qty: "148",
  createdby: "Grillo",
  img: { user10 }
}];