import {
  expireProduct01,
  expireProduct02,
  expireProduct03,
  expireProduct04,
  stockImg02,
  stockImg03,
  stockImg04,
  stockImg05,
  stockImg06,
  stockImg1,
  user02,
  user04,
  user05,
  user08,
  user09,
  user10,
  user11,
  user13,
  user30,
  user32 } from
"../../utils/imagepath";

export const ReviewsData = [
{
  id: "1",
  image: stockImg1,
  Product_Name: "Lenovo IdeaPad 3",
  Author: "James Kirwin",
  User_image: user30,
  Review: "Sleek design and excellent battery life",
  Ratings: "",
  Date: "24 Dec 2024",
  Status: "Published"
},
{
  id: "2",
  image: stockImg06,
  Product_Name: "Beats Pro",
  Author: "Francis Chang",
  User_image: user13,
  Review: "Crystal-clear sound and deep bass",
  Ratings: "",
  Date: "10 Dec 2024",
  Status: "Published"
},
{
  id: "3",
  image: stockImg02,
  Product_Name: "Nike Jordan",
  Author: "Antonio Engle",
  User_image: user11,
  Review: "Stylish, durable, and incredibly comfortable",
  Ratings: "",
  Date: "27 Nov 2024",
  Status: "Published"
},
{
  id: "4",
  image: stockImg03,
  Product_Name: "Apple Series 5 Watch",
  Author: "Leo Kelly",
  User_image: user32,
  Review: "Ultimate fitness and lifestyle companion!",
  Ratings: "",
  Date: "18 Nov 2024",
  Status: "Published"
},
{
  id: "5",
  image: stockImg04,
  Product_Name: "Amazon Echo Dot",
  Author: "Annette Walker",
  User_image: user02,
  Review: "Perfect voice-controlled home assistant!",
  Ratings: "",
  Date: "06 Nov 2024",
  Status: "Published"
},
{
  id: "6",
  image: stockImg05,
  Product_Name: "Sanford Chair Sofa",
  Author: "John Weaver",
  User_image: user05,
  Review: "Elegant design and superb comfort",
  Ratings: "",
  Date: "25 Oct 2024",
  Status: "Published"
},
{
  id: "7",
  image: expireProduct01,
  Product_Name: "Red Premium Satchel",
  Author: "Gary Hennessy",
  User_image: user08,
  Review: "perfect for work, travel, and everyday use",
  Ratings: "",
  Date: "14 Oct 2024",
  Status: "Published"
},
{
  id: "8",
  image: { expireProduct02 },
  Product_Name: "Iphone 14 Pro",
  Author: "Eleanor Panek",
  User_image: user04,
  Review: "Powerful performance and stunning display",
  Ratings: "",
  Date: "03 Oct 2024",
  Status: "Published"
},
{
  id: "9",
  image: expireProduct03,
  Product_Name: "Gaming Chair",
  Author: "William Levy",
  User_image: user09,
  Review: "Ergonomic and incredibly comfortable",
  Ratings: "",
  Date: "20 Sep 2024",
  Status: "Published"
},
{
  id: "10",
  image: expireProduct04,
  Product_Name: "Borealis Backpack",
  Author: "Charlotte Klotz",
  User_image: user10,
  Review: "Perfect for work, school and travel!",
  Ratings: "",
  Date: "10 Sep 2024",
  Status: "Published"
},
{
  id: "11",
  image: expireProduct04,
  Product_Name: "Borealis Backpack",
  Author: "Charlotte Klotz",
  User_image: user10,
  Review: "perfect for work, travel, and everyday use",
  Ratings: "",
  Date: "03 Oct 2024",
  Status: "Published"
}];