import {
  product1,
  product2,
  product3,
  product4,
  product5,
  product6,
  user02,
  user03,
  user05,
  user06,
  user12,
  user22,
  user27 } from
"../../utils/imagepath";

export const salersretrunsdata = [
{
  id: 1,
  img: { product1 },
  productname: "Macbook pro",
  date: "19 Nov 2022",
  customer: "Thomas",
  customer_image: { user27 },
  status: "Received",
  grandtotal: "550",
  paid: "120",
  due: "550",
  paymentstatus: "Paid"
},
{
  id: 2,
  img: { product2 },
  productname: "Orange",
  date: "19 Nov 2022",
  customer: "Benjamin",
  customer_image: { user02 },
  status: "Pending",
  grandtotal: "550",
  paid: "120",
  due: "550",
  paymentstatus: "Unpaid"
},
{
  id: 3,
  img: { product3 },
  productname: "Pineapple",
  date: "19 Nov 2022",
  customer: "James",
  customer_image: { user05 },
  status: "Pending",
  grandtotal: "210",
  paid: "120",
  due: "210",
  paymentstatus: "Unpaid"
},
{
  id: 4,
  img: { product4 },
  productname: "Strawberry",
  date: "19 Nov 2022",
  customer: "Bruklin",
  customer_image: { user03 },
  status: "Received",
  grandtotal: "210",
  paid: "120",
  due: "210",
  paymentstatus: "Paid"
},
{
  id: 5,
  img: { product5 },
  productname: "Macbook Pro",
  date: "19 Nov 2022",
  customer: "Best Power Tools",
  customer_image: { user22 },
  status: "Received",
  grandtotal: "210",
  paid: "120",
  due: "210",
  paymentstatus: "Paid"
},
{
  id: 6,
  img: { product5 },
  productname: "Avocat",
  date: "19 Nov 2022",
  customer: "Beverly",
  customer_image: { user12 },
  status: "Pending",
  grandtotal: "210",
  paid: "120",
  due: "210",
  paymentstatus: "Unpaid"
},
{
  id: 7,
  img: { product6 },
  productname: "Apple Earpods",
  date: "19 Nov 2022",
  customer: "Apex Computers",
  customer_image: { user06 },
  status: "Pending",
  grandtotal: "1000",
  paid: "500",
  due: "1000",
  paymentstatus: "Partial"
}];